import {
  Home,
  Calendar,
  Target,
  BookOpen,
  Library,
  FlaskConical,
  NotebookPen,
  FileText,
  Brain,
  RefreshCw,
  ClipboardCheck,
  Timer,
  BarChart3,
  Settings,
} from 'lucide-react'

export const navigationItems = [
  { path: '/', label: 'Home', icon: Home },
  { path: '/calendar', label: 'Calendar', icon: Calendar },
  { path: '/todays-mission', label: "Today's Mission", icon: Target },
  { path: '/subjects', label: 'Subjects', icon: BookOpen },
  { path: '/resources', label: 'Resources', icon: Library },
  { path: '/pyqs', label: 'PYQs', icon: FlaskConical },
  { path: '/notes', label: 'Notes', icon: NotebookPen },
  { path: '/formula-sheets', label: 'Formula Sheets', icon: FileText },
  { path: '/memory-sheets', label: 'Memory Sheets', icon: Brain },
  { path: '/active-recall', label: 'Active Recall', icon: RefreshCw },
  { path: '/mock-tests', label: 'Mock Tests', icon: ClipboardCheck },
  { path: '/study-timer', label: 'Study Timer', icon: Timer },
  { path: '/analytics', label: 'Analytics', icon: BarChart3 },
  { path: '/settings', label: 'Settings', icon: Settings },
]
