import { TASK_TYPES } from './dailyStudyConstants'

/**
 * PLANNER CONSTANTS
 * =================
 * Sprint 19B — Adaptive Daily Planner.
 *
 * Shared vocabulary for the Planner Service, the planner hooks
 * (useDailyPlanner / usePlannerOrder / usePlannerSettings) and the
 * planner UI (components/planner/*). Kept free of any React/icon imports
 * so the engine layer stays a plain data module, mirroring
 * dailyStudyConstants.js from Sprint 19A.
 */

export const TIME_BLOCKS = {
  MORNING: 'Morning',
  AFTERNOON: 'Afternoon',
  EVENING: 'Evening',
  FLEXIBLE: 'Flexible',
}

export const TIME_BLOCK_ORDER = [
  TIME_BLOCKS.MORNING,
  TIME_BLOCKS.AFTERNOON,
  TIME_BLOCKS.EVENING,
  TIME_BLOCKS.FLEXIBLE,
]

export const TIME_BLOCK_DESCRIPTIONS = {
  [TIME_BLOCKS.MORNING]: 'Deep learning — new reading & video',
  [TIME_BLOCKS.AFTERNOON]: 'Practice — problem solving',
  [TIME_BLOCKS.EVENING]: 'Revision — light review',
  [TIME_BLOCKS.FLEXIBLE]: 'Anytime — recall & notes',
}

/**
 * PLACEHOLDER LOGIC, BY DESIGN (no AI, no automatic scheduling):
 * a fixed, explainable rule that buckets each task type into the block
 * where that kind of work best fits a typical study day. This only picks
 * a task's *default* block the first time the plan for a day is built —
 * after that, the user's own Move Up/Down and any future "move" actions
 * take over via usePlannerOrder's stored order.
 */
export const TASK_TYPE_DEFAULT_BLOCK = {
  [TASK_TYPES.READ_BOOK]: TIME_BLOCKS.MORNING,
  [TASK_TYPES.WATCH_VIDEO]: TIME_BLOCKS.MORNING,
  [TASK_TYPES.SOLVE_PYQS]: TIME_BLOCKS.AFTERNOON,
  [TASK_TYPES.REVISE_FORMULA_SHEET]: TIME_BLOCKS.EVENING,
  [TASK_TYPES.REVISE_MEMORY_SHEET]: TIME_BLOCKS.EVENING,
  [TASK_TYPES.ACTIVE_RECALL]: TIME_BLOCKS.FLEXIBLE,
  [TASK_TYPES.NOTES_REVISION]: TIME_BLOCKS.FLEXIBLE,
}

/** Planner Settings — UI only. Nothing reads these to drive scheduling (see PRD / sprint scope). */
export const PLANNER_SETTINGS_FIELDS = [
  {
    key: 'dailyStudyHours',
    label: 'Daily Study Hours',
    unit: 'hrs',
    min: 1,
    max: 16,
    step: 0.5,
  },
  {
    key: 'preferredSessionLength',
    label: 'Preferred Session Length',
    unit: 'min',
    min: 10,
    max: 120,
    step: 5,
  },
  {
    key: 'breakLength',
    label: 'Break Length',
    unit: 'min',
    min: 5,
    max: 60,
    step: 5,
  },
  {
    key: 'maxTasksPerDay',
    label: 'Maximum Tasks Per Day',
    unit: 'tasks',
    min: 1,
    max: 20,
    step: 1,
  },
]

export const DEFAULT_PLANNER_SETTINGS = {
  dailyStudyHours: 6,
  preferredSessionLength: 45,
  breakLength: 10,
  maxTasksPerDay: 8,
}

/**
 * Tomorrow Preview — explicitly placeholder data per the Sprint 19B spec.
 * Not generated by the Daily Study Service; the planner is only wired to
 * receive real "tomorrow" data from the syllabus engine in a later sprint.
 */
export const TOMORROW_PREVIEW_PLACEHOLDER = [
  {
    id: 'tomorrow-placeholder-1',
    name: 'Read: Griffiths Ch. 3 — Special Techniques',
    subject: 'Electrodynamics',
    chapter: 'Special Techniques',
    topic: 'Method of Images',
    estimatedMinutes: 45,
    priority: 'High',
  },
  {
    id: 'tomorrow-placeholder-2',
    name: 'Solve PYQs — Special Techniques',
    subject: 'Electrodynamics',
    chapter: 'Special Techniques',
    topic: 'Method of Images',
    estimatedMinutes: 40,
    priority: 'High',
  },
  {
    id: 'tomorrow-placeholder-3',
    name: 'Revise Formula Sheet — Boundary Value Problems',
    subject: 'Electrodynamics',
    chapter: 'Special Techniques',
    topic: 'Boundary Value Problems',
    estimatedMinutes: 15,
    priority: 'Medium',
  },
  {
    id: 'tomorrow-placeholder-4',
    name: 'Active Recall — Boundary Value Problems',
    subject: 'Electrodynamics',
    chapter: 'Special Techniques',
    topic: 'Boundary Value Problems',
    estimatedMinutes: 20,
    priority: 'Medium',
  },
]
