import { useMemo, useState } from 'react'
import { BookOpen, CheckCircle2, Clock3, ExternalLink, GraduationCap, ListChecks, PlayCircle, Search, Timer } from 'lucide-react'
import { StudyTimerProvider, useStudyTimer } from '../context/StudyTimerContext'
import EndSessionModal from '../components/timer/EndSessionModal'
import TimerDisplay from '../components/timer/TimerDisplay'
import TimerControls from '../components/timer/TimerControls'
import FocusTargetPanel from '../components/timer/FocusTargetPanel'
import { BONUS_TOPICS, PHASES, PHASE_B_TIERS, ROADMAP_TOPICS } from '../data/roadmapBlueprintV2'
import { getQuestionBank, getQuestionById } from '../engine/pyq/questionBankService'
import bookCatalog from '../data/library/books.json'

const tabs = [{ id: 'roadmap', label: 'Roadmap', icon: ListChecks }, { id: 'subjects', label: 'Subjects', icon: GraduationCap }, { id: 'pyqs', label: 'Question Bank', icon: BookOpen }, { id: 'focus', label: 'Focus Timer', icon: Timer }]
const normalize = (value) => String(value ?? '').toLowerCase()

function BookStatus({ label }) {
  const book = (bookCatalog.books ?? []).find((item) => normalize(label).includes(normalize(item.author)) || normalize(label).includes(normalize(item.title).slice(0, 18)))
  return <div className="rounded-md border border-[#3c3c3c] bg-[#1e1e1e] p-3"><p className="text-[10px] uppercase tracking-wide text-[#6e6e6e]">Book source</p><p className="mt-1 text-xs font-medium text-[#cccccc]">{label}</p><p className="mt-1 text-[10px] text-[#858585]">{book?.path ? 'Library path is configured.' : 'Placeholder — add the file path in books.json when ready.'}</p></div>
}

function QuestionPreview({ query, onOpen }) {
  const questions = useMemo(() => getQuestionBank({ query }).slice(0, 5), [query])
  if (!questions.length) return <p className="text-[11px] text-[#6e6e6e]">No indexed PYQs match this topic yet.</p>
  return <div className="grid gap-1.5 sm:grid-cols-2">{questions.map((question) => <button key={question.id} type="button" onClick={() => onOpen(question.id)} className="rounded-md border border-[#3c3c3c] bg-[#1e1e1e] p-2 text-left hover:border-[#0e639c]"><span className="block text-[11px] font-medium text-[#cccccc]">GATE {question.year} · Q{question.questionNumber}</span><span className="mt-0.5 block truncate text-[10px] text-[#858585]">{question.subtopic}</span></button>)}</div>
}

function TopicCard({ topic, onOpenQuestion }) {
  const [open, setOpen] = useState(false)
  return <article className="rounded-lg border border-[#3c3c3c] bg-[#252526]"><button type="button" onClick={() => setOpen((value) => !value)} className="flex w-full items-start gap-3 p-4 text-left"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-md border border-[#3c3c3c] bg-[#1e1e1e] text-[11px] text-[#4fc1ff]">{topic.order}</span><span className="min-w-0 flex-1"><span className="block text-sm font-medium text-[#e8e8e8]">{topic.title}</span><span className="mt-1 block text-[11px] text-[#858585]">{topic.subject} · {topic.depth}</span></span><span className="text-xs text-[#858585]">{open ? '−' : '+'}</span></button>{open && <div className="grid gap-3 border-t border-[#3c3c3c] p-4 lg:grid-cols-[1fr_1fr]"><div className="flex flex-col gap-3"><p className="text-xs leading-relaxed text-[#bdbdbd]">{topic.reason}</p><BookStatus label={topic.book} />{topic.videoUrl ? <a href={topic.videoUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1.5 self-start rounded-md border border-[#0e639c] px-3 py-2 text-xs text-[#4fc1ff] hover:bg-[#0e639c]/10"><PlayCircle size={14} />Video source: {topic.videoLabel}<ExternalLink size={12} /></a> : <div className="rounded-md border border-dashed border-[#3c3c3c] p-3 text-[11px] text-[#858585]">Video source placeholder — add a URL in roadmapBlueprintV2.js when you choose one.</div>}<p className="text-[10px] text-[#6e6e6e]">App chapters: {topic.chapters.join(' · ')}</p></div><div><p className="mb-2 text-[10px] uppercase tracking-wide text-[#6e6e6e]">Embedded PYQs</p><QuestionPreview query={topic.pyqQuery} onOpen={onOpenQuestion} /></div></div>}</article>
}

function Roadmap({ onOpenQuestion }) {
  const [phase, setPhase] = useState('phase-a')
  const visible = ROADMAP_TOPICS.filter((topic) => topic.phase === phase)
  return <div className="flex flex-col gap-5"><header><p className="text-xs uppercase tracking-[0.2em] text-[#4fc1ff]">JEST + JAM 2027</p><h1 className="mt-1 text-2xl font-semibold text-[#e8e8e8]">Roadmap</h1><p className="mt-2 max-w-3xl text-sm leading-relaxed text-[#9d9d9d]">Your roadmap.md is the source of truth. Follow Phase 1 chronologically, use only PYQs during the JAM lockdown, then move through ranked JEST tiers.</p></header><div className="flex flex-wrap gap-2">{PHASES.map((item) => <button key={item.id} type="button" onClick={() => setPhase(item.id)} className={`rounded-md border px-3 py-2 text-xs ${phase === item.id ? 'border-[#0e639c] bg-[#0e639c] text-white' : 'border-[#3c3c3c] text-[#cccccc] hover:border-[#4a4a4a]'}`}>{item.label}</button>)}</div>{phase === 'phase-a' && <div className="flex flex-col gap-2">{visible.map((topic) => <TopicCard key={topic.id} topic={topic} onOpenQuestion={onOpenQuestion} />)}</div>}{phase === 'jam-lockdown' && <section className="rounded-lg border border-[#5a4a1d] bg-[#2b2419] p-5"><h2 className="text-base font-semibold text-[#e2c08d]">Pure PYQ window</h2><p className="mt-2 text-sm leading-relaxed text-[#d2b48c]">From 20 January until JAM: no new theory. Run timed PYQs, review errors, drill formula sheets, and use the focus timer for short targeted blocks.</p></section>}{phase === 'phase-b' && <section className="flex flex-col gap-3">{Object.entries(PHASE_B_TIERS).map(([tier, items]) => <article key={tier} className="rounded-lg border border-[#3c3c3c] bg-[#252526] p-4"><h2 className="text-sm font-semibold text-[#e8e8e8]">{tier}</h2><ol className="mt-3 grid gap-1.5 sm:grid-cols-2">{items.map((item, index) => <li key={item} className="rounded-md border border-[#3c3c3c] bg-[#1e1e1e] px-3 py-2 text-xs text-[#bdbdbd]"><span className="mr-2 font-mono text-[#6e6e6e]">{index + 1}.</span>{item}</li>)}</ol></article>)}</section>}{phase === 'jest-lockdown' && <section className="rounded-lg border border-[#5a1d1d] bg-[#2b1d1d] p-5"><h2 className="text-base font-semibold text-[#f3b4b4]">Final 10-day lockdown</h2><p className="mt-2 text-sm leading-relaxed text-[#d9a9a9]">Timed mocks, PYQs, formula sheets and mistake logs only. Prioritise Part B accuracy and attempt every NAT with any partial method.</p></section>}<section className="rounded-lg border border-[#3c3c3c] bg-[#252526] p-4"><h2 className="text-sm font-semibold text-[#e8e8e8]">Phase 1 bonus — only when ahead</h2><p className="mt-1 text-[11px] text-[#858585]">If a core topic is unfinished, this is not your current list.</p><ol className="mt-3 grid gap-1.5 sm:grid-cols-2">{BONUS_TOPICS.map((item, index) => <li key={item} className="rounded-md border border-[#3c3c3c] bg-[#1e1e1e] px-3 py-2 text-xs text-[#bdbdbd]"><span className="mr-2 font-mono text-[#6e6e6e]">{index + 1}.</span>{item}</li>)}</ol></section></div>
}

function Subjects({ onOpenQuestion }) { const [subject, setSubject] = useState('All'); const subjects = ['All', ...new Set(ROADMAP_TOPICS.map((topic) => topic.subject))]; const topics = subject === 'All' ? ROADMAP_TOPICS : ROADMAP_TOPICS.filter((topic) => topic.subject === subject); return <div className="flex flex-col gap-4"><header><h1 className="text-2xl font-semibold text-[#e8e8e8]">Subjects</h1><p className="mt-1 text-sm text-[#9d9d9d]">Resources and PYQs follow the new chronological blueprint.</p></header><div className="flex flex-wrap gap-2">{subjects.map((name) => <button key={name} type="button" onClick={() => setSubject(name)} className={`rounded-full border px-3 py-1.5 text-xs ${subject === name ? 'border-[#0e639c] bg-[#0e639c] text-white' : 'border-[#3c3c3c] text-[#cccccc]'}`}>{name}</button>)}</div><div className="flex flex-col gap-2">{topics.map((topic) => <TopicCard key={topic.id} topic={topic} onOpenQuestion={onOpenQuestion} />)}</div></div> }

function QuestionViewer({ questionId, onBack }) { const question = getQuestionById(questionId); if (!question) return null; return <div className="flex flex-col gap-4"><button onClick={onBack} type="button" className="self-start text-xs text-[#4fc1ff]">← Back to question bank</button><header><p className="text-[10px] uppercase tracking-wide text-[#858585]">{question.exam} {question.year} · Q{question.questionNumber}</p><h1 className="mt-1 text-xl font-semibold text-[#e8e8e8]">{question.subtopic}</h1></header>{question.questionImageUrl && <div className="overflow-auto rounded-lg border border-[#3c3c3c] bg-white p-2"><img src={question.questionImageUrl} alt={`Question ${question.questionNumber}`} className="mx-auto max-w-full" /></div>}<details className="rounded-lg border border-[#3c3c3c] bg-[#252526] p-4"><summary className="cursor-pointer text-xs font-medium text-[#cccccc]">Show OCR text</summary><pre className="mt-3 whitespace-pre-wrap text-xs leading-relaxed text-[#bdbdbd]">{question.ocrText}</pre></details></div> }

function QuestionBank({ onOpenQuestion }) { const [query, setQuery] = useState(''); const results = useMemo(() => getQuestionBank({ query }).slice(0, 80), [query]); return <div className="flex flex-col gap-4"><header><h1 className="text-2xl font-semibold text-[#e8e8e8]">Question Bank</h1><p className="mt-1 text-sm text-[#9d9d9d]">Search the extracted GATE Physics PYQs and open each scanned question directly.</p></header><label className="flex items-center gap-2 rounded-md border border-[#3c3c3c] bg-[#252526] px-3"><Search size={15} className="text-[#858585]" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search a topic or concept" className="w-full bg-transparent py-2.5 text-sm text-[#e8e8e8] outline-none" /></label><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{results.map((question) => <button key={question.id} type="button" onClick={() => onOpenQuestion(question.id)} className="rounded-lg border border-[#3c3c3c] bg-[#252526] p-3 text-left hover:border-[#0e639c]"><p className="text-[10px] uppercase tracking-wide text-[#858585]">GATE {question.year} · Q{question.questionNumber}</p><p className="mt-1 text-xs font-medium text-[#e8e8e8]">{question.subtopic}</p><p className="mt-1 line-clamp-2 text-[10px] text-[#858585]">{question.chapter} · {question.topic}</p></button>)}</div></div> }

function Focus() { const { status, elapsedMs } = useStudyTimer(); return <div className="mx-auto flex w-full max-w-3xl flex-col gap-5"><header className="text-center"><p className="text-xs uppercase tracking-[0.2em] text-[#4fc1ff]">Deep work</p><h1 className="mt-1 text-2xl font-semibold text-[#e8e8e8]">Focus Timer</h1></header><section className="flex flex-col items-center gap-6 rounded-xl border border-[#3c3c3c] bg-[#252526] p-8"><span className="rounded-full border border-[#3c3c3c] px-3 py-1 text-[10px] uppercase text-[#9d9d9d]">{status}</span><TimerDisplay elapsedMs={elapsedMs} /><TimerControls /></section><FocusTargetPanel /></div> }

function Shell() { const [tab, setTab] = useState('roadmap'); const [questionId, setQuestionId] = useState(null); const content = questionId ? <QuestionViewer questionId={questionId} onBack={() => setQuestionId(null)} /> : tab === 'roadmap' ? <Roadmap onOpenQuestion={setQuestionId} /> : tab === 'subjects' ? <Subjects onOpenQuestion={setQuestionId} /> : tab === 'pyqs' ? <QuestionBank onOpenQuestion={setQuestionId} /> : <Focus />; return <div className="min-h-dvh bg-[#1e1e1e] text-[#e8e8e8]"><header className="sticky top-0 z-10 border-b border-[#3c3c3c] bg-[#1e1e1e]/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-4 py-3 sm:px-6"><div><p className="text-sm font-semibold">Physics OS</p><p className="text-[10px] text-[#858585]">JAM + JEST study system</p></div><nav className="flex gap-1 overflow-x-auto">{tabs.map(({ id, label, icon: Icon }) => <button key={id} type="button" onClick={() => { setTab(id); setQuestionId(null) }} className={`inline-flex shrink-0 items-center gap-1.5 rounded-md px-3 py-2 text-xs ${tab === id && !questionId ? 'bg-[#0e639c] text-white' : 'text-[#9d9d9d] hover:bg-[#2d2d2d] hover:text-[#e8e8e8]'}`}><Icon size={14} />{label}</button>)}</nav></div></header><main className="mx-auto max-w-7xl px-4 py-6 sm:px-6">{content}</main></div> }

export default function StudyOSApp() { return <StudyTimerProvider><Shell /><EndSessionModal /></StudyTimerProvider> }
